<a href="https://colab.research.google.com/github/Ralph2g/Pandas_course/blob/master/8_Concat_%26_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/Drive/')
import pandas as pd
import numpy as np

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/Drive/


In [5]:
pd.options.display.float_format = '{:.2f}'.format

In [6]:
# Hace lo mismo que float_format
np.set_printoptions(precision=2)

In [7]:
np.random.rand()

0.5979422287605921

In [8]:
x1 = np.random.randn(2,5)*100
x1

array([[  -3.38,   25.2 ,  -69.08, -171.75,   -8.82],
       [ -81.41,  149.51,  -42.41, -172.67,   59.02]])

In [10]:
x2 = np.random.randn(2,5)*-1
x2

array([[ 0.38,  0.47, -0.06, -0.88,  0.35],
       [ 0.16,  1.08,  1.22,  0.96,  0.39]])

In [12]:
# Concatenar arreglos np
np.concatenate([x1,x2])

array([[-3.38e+00,  2.52e+01, -6.91e+01, -1.72e+02, -8.82e+00],
       [-8.14e+01,  1.50e+02, -4.24e+01, -1.73e+02,  5.90e+01],
       [ 3.84e-01,  4.70e-01, -5.95e-02, -8.80e-01,  3.47e-01],
       [ 1.65e-01,  1.08e+00,  1.22e+00,  9.55e-01,  3.91e-01]])

In [13]:
np.concatenate([x1,x2]).shape

(4, 5)

In [14]:
np.concatenate([x1,x2],axis=1)

array([[-3.38e+00,  2.52e+01, -6.91e+01, -1.72e+02, -8.82e+00,  3.84e-01,
         4.70e-01, -5.95e-02, -8.80e-01,  3.47e-01],
       [-8.14e+01,  1.50e+02, -4.24e+01, -1.73e+02,  5.90e+01,  1.65e-01,
         1.08e+00,  1.22e+00,  9.55e-01,  3.91e-01]])

In [16]:
np.concatenate([x1,x2],axis=1).shape

(2, 10)

In [17]:
# ahora hagamos las concatenaciones con pandas para esto inciemos con nuestras series

s1 = pd.Series(x1[0],index= ['a','b','c','d','e',])
s1

a     -3.38
b     25.20
c    -69.08
d   -171.75
e     -8.82
dtype: float64

In [18]:
s2 = pd.Series(x2[0],index=['c','d','e','f','g',])
s2

c    0.38
d    0.47
e   -0.06
f   -0.88
g    0.35
dtype: float64

In [19]:
# Se aplica la funcion concat a los df para poder concatenarlos
pd.concat([s1,s2])

a     -3.38
b     25.20
c    -69.08
d   -171.75
e     -8.82
c      0.38
d      0.47
e     -0.06
f     -0.88
g      0.35
dtype: float64

In [20]:
pd.concat([s1,s2],axis=1)

0     1
a   -3.38   nan
b   25.20   nan
c  -69.08  0.38
d -171.75  0.47
e   -8.82 -0.06
f     nan -0.88
g     nan  0.35

In [22]:
# Para resetear el index hacemos lo siguiente:
s1.reset_index(drop=True) #Drop elimina la columna del index

0     -3.38
1     25.20
2    -69.08
3   -171.75
4     -8.82
dtype: float64

In [24]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1)

0     1
0   -3.38  0.38
1   25.20  0.47
2  -69.08 -0.06
3 -171.75 -0.88
4   -8.82  0.35

In [26]:
## Ahora nos vamos a meter con un objeto un poco más eleborado: DataFrames

df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 3.66 3.57
1 3.00 5.06
2 0.54 2.89

In [27]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'],index=[2,3,4])
df2

a     b
2 -0.17 -0.99
3 -0.53 -0.27
4 -0.15 -0.19

In [28]:
pd.concat([df1,df2])

a     b
0  3.66  3.57
1  3.00  5.06
2  0.54  2.89
2 -0.17 -0.99
3 -0.53 -0.27
4 -0.15 -0.19

In [29]:
# para concatenar en el eje de las columnas hacemos lo siguiente:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 3.66 3.57   nan   nan
1 3.00 5.06   nan   nan
2 0.54 2.89 -0.17 -0.99
3  nan  nan -0.53 -0.27
4  nan  nan -0.15 -0.19

In [30]:
# Para solo devolver la columna en la que coinciden en la concatenación:
pd.concat([df1,df2],axis=1,join='inner')

a    b     a     b
2 0.54 2.89 -0.17 -0.99

In [31]:
# Resetenado el indice tenemos lo siguiente:

pd.concat([
           df1.reset_index(drop=True),
           df2.reset_index(drop=True)],
          axis=1)

a    b     a     b
0 3.66 3.57 -0.17 -0.99
1 3.00 5.06 -0.53 -0.27
2 0.54 2.89 -0.15 -0.19

In [32]:
# Otra manera de hace la concatenación de manera sencilla es con append
df1.append(df2).append(df2)

a     b
0  3.66  3.57
1  3.00  5.06
2  0.54  2.89
2 -0.17 -0.99
3 -0.53 -0.27
4 -0.15 -0.19
2 -0.17 -0.99
3 -0.53 -0.27
4 -0.15 -0.19

In [33]:
# Para hacerlo en el eje de las columnas se saca la transpuesta del dataframe
df1.T.append(df2.T).T

a    b     a     b
0 3.66 3.57   nan   nan
1 3.00 5.06   nan   nan
2 0.54 2.89 -0.17 -0.99
3  nan  nan -0.53 -0.27
4  nan  nan -0.15 -0.19